import colors from "../utils/colors";

export const dataChartDisciplines = [
  {
    key: 1,
    id: 0,
    value: 50,
    label: "SL",
    frontColor: colors.slColor,
    text: "18%",
    labelPosition: "outward",
    color: colors.slColor,
    textColor: "white",
    fontWeight: "bold",
  },
  {
    key: 2,
    id: 1,
    value: 80,
    label: "GS",
    frontColor: colors.gsColor,
    text: "30%",
    labelPosition: "outward",
    color: colors.gsColor,
    textColor: "white",
    fontWeight: "bold",
  },
  {
    key: 3,
    id: 2,
    value: 90,
    label: "SG",
    frontColor: colors.sgColor,
    text: "35%",
    labelPosition: "outward",
    color: colors.sgColor,
    textColor: "white",
    fontWeight: "bold",
  },
  {
    key: 4,
    id: 3,
    value: 70,
    label: "DH",
    frontColor: colors.dhColor,
    text: "23%",
    labelPosition: "outward",
    color: colors.dhColor,
    textColor: "white",
    fontWeight: "bold",
  },
  {
    key: 5,
    id: 4,
    value: 2,
    label: "FS",
    frontColor: colors.fsColor,
    text: "23%",
    labelPosition: "outward",
    color: colors.fsColor,
    textColor: "white",
    fontWeight: "bold",
  },
];
